### ISSUE TITLE
No ENABLE signal to boot the IMX290 sensor from the lattice FPGA

### ISSUE THREAD

**Issue by INDNextHenry** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#11]
Hi @circuitvalley, 
After program the fpga and usb3, finnaly I got a another issue, the IMX290 sensor board has no power. **The ENABLE signal was always low level**. I suspect that the fpga program is not normally started from the external flash, but I don't know how to verify this problem.
![Selection_048](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/13d7561d-96cf-49f0-a5ee-37c43189bb99)
The Cypress FX3 USB3 serial port output log:
![20230523-181254](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/f186b264-bc44-454b-bcd0-56ab74876238)
I think I should be very close to the final success, please help me, Thank you very much!!

**Comment by INDNextHenry** [comment]
I think I loaded the `/Cypress_FX3_USB_Firmware/Image/USB_C_FX3_CV.img` was default suit for IMX477. So the IMX290 is not working.

**Comment by circuitvalley** [comment]
You can compile img file for IMX290  your self or wait for a while I can provide you a .img file.

Regards

**Comment by circuitvalley** [comment]
To fix compile issue, Include correct file in source. and include and exclude correct file in eclipse project as well. look on internet of including or excluding files from eclipse project

**Comment by INDNextHenry** [comment]
Hi @circuitvalley 
I tried to build a fx3 project, then compile it.
![buildding](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/c7b23ddf-c89f-4bca-ab25-6aeec696e68d)
It seems to work, then I got some *.img files.
![after_build](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/83df06b2-fa5e-4cf1-8ecd-727287c6508d)
Unfortunately I still don't get the ENABLE high signal of the IMX290 board.  The ENABLE signal of the IMX290 board is sent from the lattice FPGA. 
![image](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/5effb1ac-d58e-49eb-a08f-61cafffa5987)
Although the FPGA programming is successful, I still need to investigate why the ENABLE signal is not enabled. 
![20230525-162934](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/97483c01-9458-4d64-aaea-403c9092ab7c)
I suspect that the FPGA is not functioning properly, the evidenced is the DONE signal not being pulled low as expected.
![Selection_051](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/310fd389-8dc6-4292-b42f-d2bc0fd9f6ce)
The LED2 quickly go off. 
![Selection_050](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/8bef8b57-761b-4cae-8413-08f825f7a1a4)

**Comment by INDNextHenry** [comment]
The latest status, I directly burn the program into the SRAM of the FPGA, the DONE signal is pulled low, and now the LED2 light is red.
![20230525-171902,jpg](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/14cc1555-5af5-47c4-8896-bc90e2421fea)
However, the USB serial port gives a frame timer timeout warning, I guess because the frequency of the FX3 is set to 400MHZ? and the DMA needs to be set to 32K?
![20230525-172340](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/1f27dcd4-2fdc-422a-ba94-f6553f00f1ff)

**Comment by INDNextHenry** [comment]
In a words, I success programmed the fpga, but when power off the FPGA and restart, there is no EBABLE signal to IMX290.

**Comment by nokiagx** [comment]
I'm not proficient in FPGA and I can't help you. I'm sorry！













At 2023-06-02 16:59:18, "INDNext_Henry" ***@***.***> wrote:

In a words, I success programmed the fpga, but when power off the FPGA and restart, there is no EBABLE signal to IMX290.
