### ISSUE TITLE
Version firmware ENABLE and pinout

### ISSUE THREAD

**Issue by rubenl1995** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#12]
Hi @circuitvalley thanks for your design, it's nice.

I want understand your design and need resolve any questions. I hope your help.

I'm going to use your design with sensor IMX290 but I have watched a change no implemented at pin ENABLE, this pin active XCLR from delay ENABLE in PCB IMX477 but PCB IMX290 active from FPGA. In your firmware, where can I watch this change?

In your sketch FPGA I he watched a pinout different respect your schematic, is possible different version? For example, J12 is DATA_0  but in schematic J12 is D8, it's showed in the next figure:

![Captura de pantalla 2023-07-03 125154](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/45743640/2d90f4db-2bdb-4f4b-a919-ef9ee94ae7a2)
![Captura de pantalla 2023-07-03 125231](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/45743640/aff49a9e-a6f2-4c6e-bdfb-94d62033da5b)

Thanks for your time,
Rubén

**Comment by circuitvalley** [comment]
Hello, 
Schematic D0 is At J12 , and J11 Has been fixed, These pins are data as long as all 32bit connected you can map them anywhere. 
Enable pin  is located on same location, It is driven by FPGA , You can always put a pull up to enable the Camera module permanently.

**Comment by circuitvalley** [comment]
Hello, 
Schematic D0 is At J12 , and J11 Has been fixed, These pins are data as long as all 32bit connected you can map them anywhere. 
Enable pin  is located on same location, It is driven by FPGA , You can always put a pull up to enable the Camera module permanently.
