### ISSUE TITLE
Files for debayer simulation

### ISSUE THREAD

**Issue by MohamedWHassan** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#15]
Hello,
can you upload the files used in the debayer testbench such as
italy.bmp768x512.raw
italy.bmp768x512.raw.rgb
italy.bmp768x512.raw.yuv
italy.bmp768x512.raw.verify

**Comment by circuitvalley** [comment]
Raw file is added rest of the files are auto generated during simulation. 
Commit. c76b455dc6708e8dc4d719f1ef93ee0b13e4a787

**Comment by MohamedWHassan** [comment]
Hi,

Is it possible to tell me how did you manage to obtain the .RAW file?
I'm trying to find different RAW files with different bayer pattern but no luck so far.

Thanks

**Comment by nokiagx** [comment]
Sorry, I don't know



At 2023-10-17 14:52:07, "MohamedWHassan" ***@***.***> wrote:

Hi,

Is it possible to tell me how did you manage to obtain the .RAW file?
I'm trying to find different RAW files with different bayer pattern but no luck so far.

Thanks

**Comment by kimstik** [comment]
> Hi,
> 
> Is it possible to tell me how did you manage to obtain the .RAW file? I'm trying to find different RAW files with different bayer pattern but no luck so far.
> 
> Thanks

https://swisscows.com/en/web?query=bayer+raw+image+sample
shows a lot of them:
https://stackoverflow.com/questions/27402422/where-can-i-download-raw-bayer-images
https://cs.brown.edu/courses/csci1290/labs/lab_raw/index.html

**Comment by MohamedWHassan** [comment]
@kimstik 
Thank you for the reply. But it is hard to find these RAW bayer images that could be used in the testbench as I've been looking for days.

I found this [repo](https://github.com/zhengtianyu1996/bayer_image_process) which has a img2raw matlab script and with some modifications it worked nicely.

**Comment by nokiagx** [comment]
kimstik：

I remember not posting any comments or suggestions in this field.
我记得我没有发表过这个领域的评论或建议。



At 2023-10-18 16:51:22, "MohamedWHassan" ***@***.***> wrote:

@kimstik
Thank you for the reply. But it is hard to find these RAW bayer images that could be used in the testbench as I've been looking for days.

I found this repo which has a img2raw matlab script and with some modifications it worked nicely.
