### ISSUE TITLE
FX3 logs print "DMA Reset Event: Frame timer overflow, time period = 400"

### ISSUE THREAD

**Issue by INDNextHenry** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#17]
1. After some modify, the netlist analyzer is like this:
![image](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/f00369bd-7764-488d-a457-077290bf170f)

2. After programn the FPGA bitstream file, webcamoid has nothing, and FX3 log as here, says frame timeout:
![image](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/7e36c484-a51b-4ba1-b399-024aa04ce3b1)

Not sure is which part has the issue.

**Comment by circuitvalley** [comment]
This indicates there is no packets from FPGA to USB controller, 

There are few tips I could give you. How to debug if things are not working for you.Checking FPGA

Check fpga if it is outputting pixel clock , lsync and fsync. These signals are the most important if any of the pixel(data) lines are not correct then you will get a bad image but if any one of the Clock, Fsync or Lsync are not found you will get no image. This if any of these signals are not there then it may mean a bad solder joint. You can debug by debug signal from FPGA.
Check if FPGA outputs the same number of pixels on every frame. You would either need a Physical counter instrument  or a counter implemented in an FPGA. You need to count the exact number of pixels in a Frame. If FPGA output inconsistent number of byte every frame most UVC viewer will ignore frames, These may meen no image at all or massive drop in frame depending on how inconsistent your bytes are.
Checking FX3

FX3 part can be debugged by driving GPIO from GPIF or even C code. Debug frame sync Line sync etc. 

To check if you are receiving any data at all from the camera. Then use wireshark with USBPcap to capture USB packets. You can easily find these packets and also count how many bytes FPGA is sending. 

All the source files including sensor driver are present in repo. Only the sensor selected is included in the build. EZ USB suite allows you to select and deselect source files. EZ USB is eclipse based, Search on internet how to enable disable source in eclipse.4. If you are having a hard time resetting senor then it can be either permanently held out of reset with pull up or you can check how and which pins FPGA drive for resetting.
Sorry I do not have time for individual image builds. 
Regards
