### ISSUE TITLE
The connector pins between FX3 and FPGA boards are mismatch

### ISSUE THREAD

**Issue by INDNextHenry** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#19]
Hi @circuitvalley 

I found that there are 3 pairs of pins on the upper connector of the FPGA and the lower connector of the USB3-FX3 that do not match, and the remaining 50 or so pins match normally. Is this a mistake or is it intentional design?

![Selection_277](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/21068a3e-b723-4630-bbe6-d85fdc108159)

**Comment by mca312** [comment]
Any luck on this? I’m about to start on a prototype

**Comment by INDNextHenry** [comment]
> Any luck on this? I’m about to start on a prototype

No one mentioned this point, and very few people put this project into practical action.

**Comment by circuitvalley** [comment]
Only names are in correct, This is fixed in constrain files pin assignment,
