### ISSUE TITLE
What other sensors does it support?

### ISSUE THREAD

**Issue by maifeeulasad** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#22]
As per documentation we only have support for `IMX477`, `IMX219`, `IMX290`, `IMX327`, `IMX462` these sensors. What other sensors does it support?

**Comment by circuitvalley** [comment]
Any Sensor from which Support RAW10 to RAW14 Will work as is as long as its MIPI and you have I2C driver for initializing.

**Comment by maifeeulasad** [comment]
Thanks for the details really appreciate it.

**Comment by circuitvalley** [comment]
@maifeeulasad  A new version of camea vailable on kickstarter with multiple sensors supported 
CHC5 World's First Open Machine Vision Camera
https://www.youtube.com/watch?v=F9n1e-QN0zk
https://www.kickstarter.com/projects/circuitvalley/chc5-open-machine-vision-programmable-industrial-camera?ref=cc2cwr
