### ISSUE TITLE
ECP5 supported?

### ISSUE THREAD

**Issue by francis2tm** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#3]
Hello,
Amazing project. I was wondering if it is possible to use this with an ECP5 FPGA?

**Comment by circuitvalley** [comment]
There are no specific restriction in place that will prevent design from getting used with ECP5 FPGA , or any other FPGA. 
ECP5 Does not have hard MIPI phy, So you would need to use soft phy, Which is basically same thing. I have already demonstrated using Soft mipi phy with Lattice MachXO3 FPGA.
