### ISSUE TITLE
Bill of Material and BOM Cost 

### ISSUE THREAD

**Issue by cliffchar** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#4]
Do you have Bill of Material and also have any idea how much is BOM cost?

**Comment by circuitvalley** [comment]
BOM excel list are present in the under hardware in the repo. 

BOM cost is as follows with no tax and no shipping , these are mouser/digikey prices , so there is improvement possible
FX3 Board
QTY 1 , QTY10 QTY 500
60 EUR , 50 EUR , 35 EUR
Crosslink NX
101 EUR , 78 EUR , 68 EUR
IMX290/462 Camera
41 EUR , 32 EUR , 25 EUR

Total for Just PCBs
QTY 1 , QTY10 , QTY500
202 EUR , 170 EUR , 128 EUR

Enclosure and lens would be additional
