### ISSUE TITLE
Future support for larger sensors?

### ISSUE THREAD

**Issue by edward-io** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#5]
Really cool project! Theoretically, could the camera support 
 4/3" sensors os larger? For example: IMX269, IMX272, IMX271, IMX571.

**Comment by circuitvalley** [comment]
There is no specific limit on sensor size, it's just matter of making needed adjust to enclosure, and make a suitable lens mount. As long as camera has MIPI CSI interface my design could be used as is. 
I have just made commit with IMX477 files.

Regards

**Comment by circuitvalley** [comment]
For future plans, I will possibly make camera with IMX294 as I have designs ready with that sensor.

**Comment by circuitvalley** [comment]
Do you have any idea where one could possibly find sensor to buy any of your IMX269, IMX272, IMX271, IMX571.
