### ISSUE TITLE
OotoPart BOMs?

### ISSUE THREAD

**Issue by jleppert** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#6]
Thanks for publishing this amazing project! I am putting together an OctoPart BOMs for the boards, can you kindly review this one for FPGA board BOM?

https://octopart.com/bom-tool/CdZ11cSl

Thank you!

**Comment by circuitvalley** [comment]
Thank you for your time. I am looking into the it.

**Comment by circuitvalley** [comment]
Appears to be all correct
