### ISSUE TITLE
some schematic is missing

### ISSUE THREAD

**Issue by james2002chen** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#7]
In the FPGA_core project，two 40 pin dense connectors J1 and J2 appear on the PCB drawing，but there's no J1 or J2 on any of the schematic currently published. Please check if files under \Hardware\02_FPGA_Core\PCB_Source is complete

**Comment by james2002chen** [comment]
![image](https://user-images.githubusercontent.com/46477673/212306432-0fe68a8c-6509-4d50-b6ef-36297b990c19.png)
from the component class, it can be told that is missing file is named "camera.SchDoc"

**Comment by circuitvalley** [comment]
Thank you for pointing, File has be added and and fixed  issue with commit #2df2c166f4f118be3986a7159f8ee61677012df9
