### ISSUE TITLE
resistor values in BOM are incorrect

### ISSUE THREAD

**Issue by james2002chen** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#8]
The resistor values in all the 3 BOM files are incorrect. 

For example, in \Hardware\01_Camera_Sensors\IMX290_IMX327_IMX462\IMX290_Module_BOM.xlsx
![image](https://user-images.githubusercontent.com/46477673/212659215-3e129098-75b9-47f3-a2de-cfffec986f71.png)
All the four resistors are annotated as "0 ohm", which doesn't match with the schematic:
![image](https://user-images.githubusercontent.com/46477673/212659397-c6c4187d-51b9-4c4c-bafd-0a13d955d1bb.png)
That's also the case in FPGA_bom and usbc_bom, causing confusion during the assembly. 

Please change the Comment field of the resistors from "Thick Film" to "=Value", and update all three BOM files.
![image](https://user-images.githubusercontent.com/46477673/212662011-42a42e51-5dcb-4c13-bbeb-d41ef89a3769.png)

**Comment by circuitvalley** [comment]
Values are correct in schematic. Please refer to schematics. You can put values into xls files and create a pull request
