### ISSUE TITLE
Does anyone success build the FPGA source code?

### ISSUE THREAD

**Issue by INDNextHenry** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#9]
1. Lattice Radiant Software. 
![Selection_046](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/adc6aff5-61bc-4542-abda-b896e61da5bb)

2. Create the project contains the all source code.
3. try to build the prroject, it failed.
4. ![Selection_045](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/8d7d7fdb-d385-4283-b3a3-9f069506e318)

But It says a syntax error:  `Industrial_Camera_FPGA/source/impl_1/mipi_csi_rx_raw_depacker_8b2lane.v(134): syntax error near ). VERI-1137`.  

Any help thanks a lot! 
[Industrial_Camera_FPGA.zip](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/files/11475406/Industrial_Camera_FPGA.zip)

**Comment by circuitvalley** [comment]
Try Creating a project without any tb_* files or disable tb_* file from project, You have wrong top module. There should be only one mipi_csi_16_nx.v as top.

**Comment by INDNextHenry** [comment]
Hi Sir @circuitvalley, 

1. I removed the Testblocks source, only add /src/*, /src/Lattice_specfic/* to the project. 
2. set the `mipi_csi_16_nx.v` as top. 

I still got a error, not sure what going on, Any help is appreciated!!! 
![Selection_053](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/a812814c-d30d-45a2-bf43-70115531ba28)

**Comment by INDNextHenry** [comment]
My bad, It has build success now. I got a typo issue.

**Comment by y-runwal** [comment]
@INDNextHenry , can you share hierarchy of successfully built project? I am facing some issues while managing files. Thank you.
